version: '3'
services: 
  web: #This can be anyname to identify the container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # Dont touch this directory
      - .:/app  # map "." -> "/app"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules  # Dont touch this directory
      - .:/app  # map "." -> "/app"
    command: ["npm", "run", "test"]